"""add_split_expenses_models

Revision ID: 8c327be61737
Revises: e482b912b9d2
Create Date: 2026-07-18 12:45:12.597614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c327be61737"
down_revision: Union[str, Sequence[str], None] = "e482b912b9d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("paid_by_member_id", sa.Uuid(), nullable=False),
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_cents > 0", name="ck_expenses_amount_cents_positive"
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paid_by_member_id", "house_id"],
            ["house_members.id", "house_members.house_id"],
            name="fk_expenses_paid_by_member_house",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "house_id", name="uq_expenses_id_house"),
    )
    op.create_table(
        "settlements",
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column("from_member_id", sa.Uuid(), nullable=False),
        sa.Column("to_member_id", sa.Uuid(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "settled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_cents > 0", name="ck_settlements_amount_cents_positive"
        ),
        sa.CheckConstraint(
            "from_member_id <> to_member_id", name="ck_settlements_different_members"
        ),
        sa.ForeignKeyConstraint(
            ["from_member_id", "house_id"],
            ["house_members.id", "house_members.house_id"],
            name="fk_settlements_from_member_house",
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_member_id", "house_id"],
            ["house_members.id", "house_members.house_id"],
            name="fk_settlements_to_member_house",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense_shares",
        sa.Column("expense_id", sa.Uuid(), nullable=False),
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_cents > 0", name="ck_expense_shares_amount_cents_positive"
        ),
        sa.ForeignKeyConstraint(
            ["expense_id", "house_id"],
            ["expenses.id", "expenses.house_id"],
            name="fk_expense_shares_expense_house",
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id", "house_id"],
            ["house_members.id", "house_members.house_id"],
            name="fk_expense_shares_member_house",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "expense_id", "member_id", name="uq_expense_shares_expense_member"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense_shares")
    op.drop_table("settlements")
    op.drop_table("expenses")
    # ### end Alembic commands ###
